### ISSUE TITLE
Kolla livestreaming och Samsungtelefoner.

### ISSUE THREAD

**Issue by nicklaslof** [Slashat/slashat-android#11]

**Comment by tommienu** [comment]
Utveckla issue:et ovan är du vänlig - vad är problemet? Har en Galaxy 2 jag kan prova med ikväll.

**Comment by nicklaslof** [comment]
Från min kontakt på bambuser:

"på HLS-streamar så buggar på en del samsungdevices, så för tillfället så kör vi bara RTSP på såna"

**Comment by tommienu** [comment]
All right, påminn mig ikväll så kollar jag med Galaxy s2.

**Comment by nicklaslof** [comment]
Works!
