### ISSUE TITLE
Koppla spelaren till huvud ui

### ISSUE THREAD

**Issue by chrillep** [Slashat/slashat-android#26]
Vet inte riktigt hur jag ska förklara men de flesta hemskärmar har någon inbyggt spelarkontroll som även kan styras ifrån låsskärmen. Kan inte APIet för detta men det borde gå å lösa.
Alt. play/pauase ifrån notifikationscentrat

**Comment by nicklaslof** [comment]
Jag förstår vad du menar. En av de sakerna som inte hann komma med i version 1.0 :)
