### ISSUE TITLE
Showarkiv: Visa 10 senaste avsnitt, knapp för att visa ner alla

### ISSUE THREAD

**Issue by tommienu** [Slashat/slashat-android#8]
Känns som att vi inte behöver precacha ner 200 ansnitt varje gång man går in i showarkiv, utan plocka ner 10 senaste och in med en knapp liknande "Se alla avsnitt". Så sparar vi lite banbredd hos användaren och så blir det lite snabbare laddningstider.

**Comment by nicklaslof** [comment]
Tjena

Min plan var att cachea rssfilen (samt serializera objekten/peta dem i en
sqlitedb) och bara plocka om filen ifall den ändrats på servern. (Typ kolla
size eller liknande innan man laddar den) och sen parsea nya filen tills
den tills den hittar entries som redan finns och stoppa där.

/Nicklas
